---
- name: Configure Internet Customer
  hosts: 192.168.1.1/27
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: semaphore
    ansible_ssh_user: semaphore
    ansible_ssh_password: semaphore
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_cli_ssh_type: paramiko
  tasks:
  - name: Activate and add description to the interfaces
    cisco.ios.ios_interfaces:
      config:
        - name: FastEthernet0/0
          description: Configured and managed by Ansible Network
          enabled: true
        - name: FastEthernet0/1
          description: WAN interface
          enabled: true
        - name: FastEthernet1/0
          description: Lan Client interface
          enabled: true
      state: merged

  - name: gather snmp configuration
    cisco.ios.ios_command:
      commands:
         - show running-config | include snmp
    register: snmp_output
  - name: check
    set_fact:
      snmp_config_present: "{ 'snmp' in snmp_output.stdout[0] }"

  - name: add snmp configuration
    cisco.ios.ios_config:
      lines:
        - snmp-server community Ansible_ro ro
        - snmp-server community Ansible_rw rw
        - snmp-server enable traps cpu threshold
        - snmp-server host 10.10.10.10 test
    when: snmp_output != snmp_config_present
	  when: False

  - name: gather AAA configuration
    cisco.ios.ios_command:
      commands:
         - show running-config | include aaa
    register: aaa_output
  - name: check AAA
    set_fact:
      aaa_config_present: "{ 'aaa new-model' in aaa_output.stdout[0] }"

  - name: add AAA
    cisco.ios.ios_config:
      lines:
        - aaa new-model
        - aaa authentication login default local
        - aaa authentication enable default enable
        - aaa authorization exec default local
        - aaa authorization commands 1 default local
        - aaa authorization commands 15 default local group tacacs+
        - aaa accounting exec default start-stop group tacacs+
        - aaa accounting commands 15 default stop-only group tacacs+
        - aaa accounting system default start-stop group tacacs+
    when: False
    
  - name: Create subinterface FastEthernet0/1.1000
    cisco.ios.ios_config:
      lines:
        - encapsulation dot1Q 1000
      parents: interface FastEthernet0/1.1000

  - name: Create subinterface FastEthernet0/1.882
    cisco.ios.ios_config:
      lines:
        - encapsulation dot1Q 882
      parents: interface FastEthernet0/1.882

  - name: Configure FastEthernet0/1.1000 - Service
    cisco.ios.ios_l3_interfaces:
      config:
        - name: FastEthernet0/1.1000
          ipv4:
            - address: 20.20.20.20/31
      state: merged

  - name: Configure FastEthernet0/1.882 - Supervision
    cisco.ios.ios_l3_interfaces:
      config:
        - name: FastEthernet0/1.882
          ipv4:
            - address: 192.168.1.1/27
      state: merged

  - name: Configure FastEthernet1/0 - LAN CLIENT
    cisco.ios.ios_l3_interfaces:
      config:
        - name: FastEthernet1/0
          ipv4:
            - address: 4.4.4.0/30
      state: merged

  - name: Configure static route service
    cisco.ios.ios_static_routes:
      config:
        - address_families:
          - afi: ipv4
            routes:
              - dest: 0.0.0.0/0
                next_hops:
                  - forward_router_address: 20.20.20.19
                    name: default_route_service
    when: add_default_route

  - name: Configure static route Supervision
    cisco.ios.ios_static_routes:
      config:
        - address_families:
          - afi: ipv4
            routes:
              - dest: 10.55.55.64/26
                next_hops:
                  - forward_router_address: 192.167.1.2
                    name: supervision_route
      state: merged

  - name: Configuration BGP with route-map
    cisco.ios.ios_bgp_global:
      config:
        as_number: 65000
        bgp:
          log_neighbor_changes: true
        neighbor:
          - address: 20.20.20.19
            description: ISP neighbor
            remote_as: 65001
            route_map:
              name: Advertised_routes
              out: true
      state: merged
    when: add_bgp

  - name: Prefix lists configuration
    cisco.ios.ios_prefix_lists:
      config:
        - afi: ipv4
          prefix_lists:
            - name: Advertised_routes
              description: allow lans to be advertised to bgp neighber
              entries:
                - action: permit
                  prefix: 4.4.4.0/30
                  sequence: 5
      state: merged
    when: add_bgp

  - name: Route maps configuration
    cisco.ios.ios_route_maps:
      config:
        - route_map: Advertised_routes
          entries:
            - sequence: 10
              action: permit
              description: Advertised_routes
              match:
                ip:
                  address:
                    prefix_lists:
                      - Advertised_routes
            - sequence: 20
              action: deny
              description: Advertised_routes
      state: merged
    when: add_bgp

  - name: save configuration
    cisco.ios.ios_config:
      save_when: modified
	
  - name: Configure VLAN 1000
      vlan:
        vlan_id: 1000
        state: present

    - name: Configure WAN Interface
      ip_interface:
        interface: WAN
        ip: 20.20.20.20/31/31
        state: present

    - name: Configure Gateway
      ip_route:
        network: 0.0.0.0/0
        gateway: 20.20.20.19
        state: present
      when: True

    - name: Configure Management Interface
      ip_interface:
        interface: Management
        ip: 192.168.1.1/27
        state: present

    - name: Configure AAA
      # Add your AAA configuration task here
      # Example: aaa_configuration_task:
      #   option: value
      when: False

    - name: Configure SNMP
      # Add your SNMP configuration task here
      # Example: snmp_configuration_task:
      #   option: value
      when: False
    